# Generated by Django 3.2.7 on 2021-10-19 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('create_at', models.DateTimeField(verbose_name='Create at')),
                ('update_at', models.DateTimeField(verbose_name='Update at')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='child', to='core.category', verbose_name='Parent')),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=512, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Post Content')),
                ('create_at', models.DateTimeField(verbose_name='Publish at')),
                ('update_at', models.DateTimeField(verbose_name='Update at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.category', verbose_name='Category')),
            ],
        ),
    ]
