# Generated by Django 3.2.7 on 2021-10-21 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211021_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default='self', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='child', to='core.category', verbose_name='Parent'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts', to='core.Category', verbose_name='Category'),
        ),
    ]
