# Generated by Django 3.2.7 on 2021-10-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211022_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='json_content',
            field=models.JSONField(null=True, verbose_name='Json'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category', related_query_name='category', to='core.Category', verbose_name='category'),
        ),
    ]
