# Generated by Django 3.2.7 on 2021-10-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211022_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='json_content',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category', related_query_name='category', to='core.Category', verbose_name='category'),
        ),
    ]
